feat: CQDG-354 add juno qa cert
Ferlab-Ste-Justine/spark-images pull request #33
Opened 2023-09-06 19:25 UTC by adipaul1981

2023-09-06 19:29 UTC, creativeyann17 requested changes

2023-09-06 19:29 UTC, creativeyann17 commented on install_ca.sh
> +    keytool -noprompt -importcert -trustcacerts -cacerts -alias cqdg-es -storepass changeit -file /opt/ca_cqdg_juno_qa.der
l'alias `cqdg-es` est deja utilise en mettre un autre

2023-09-06 19:31 UTC, adipaul1981 commented on install_ca.sh
> +    keytool -noprompt -importcert -trustcacerts -cacerts -alias cqdg-es -storepass changeit -file /opt/ca_cqdg_juno_qa.der
Merci!

2023-09-06 19:51 UTC, creativeyann17 approved these changes

2023-09-07 12:07 UTC, closed without merging

2023-09-07 12:08 UTC, adipaul1981 commented
New one was oppened